### ISSUE TITLE
File Upload Test Cases

### ISSUE THREAD

**Issue by RFSH** [informatics-isi-edu/chaise#1152]
A create/edit scenario for file upload is as follows, 
1. ERMrestjs parses the annotaion and visible columns correctly.
2. Chaise shows the correct UI for uploading file.
3. ERMrestjs generates a correct checksum.
4. ERMrestjs and Chaise show the upload progress.
5. ERMrestjs returns the final url on upload completion.
6. Chaise saves the meta data and shows the result page (it can be record page or the recordedit success page).

We can test file upload for 8 different scenarios with various combinations of create/edit, single/multiple record(s), and single/multiple asset column(s) in table.  Among them, these scenarios are more important and should be tested:
- Create multiple records
  - [ ] Table with one asset:  chaise e2e test (steps ~~2~~, 6)
  - [ ] Table with multiple assets: emrestjs unit test (steps 3, 5, 6)
- Edit one record
  - [x] Table with one asset: chaise e2e test (steps 2, 6)
  - [ ] Table with multiple assets: ermestjs unit test (steps 3, 5, 6)
- Edit multiple records
  - [ ] Table with multiple assets: chaise e2e test (steps 2, 6)

We should also test three different scenarios for generating an asset `url_pattern`, when it is,
1. A combination of one of visible columns and md5 (for both edit and create). 
2. A combination of one of generated visible columns and md5 (for edit).
3. A combination of one of generated invisible columns and md5 (for edit). 

Other part of test involves the pause/resume logic. The important features that needs to be tested are: abort and resuming the upload, progress bar, retry logic when facing 500 and terminal errors. We first have to test these features in ermestjs and make sure they are working as expected. Then we can test the "step 6" in both ermrestjs and chaise, using pause/resume features.

**When we are testing file upload, we should us `/hatrac/js/` prefix for `url_pattern`. So then we can easily remove uploaded test files.**

**Comment by RFSH** [comment]
I am closing this issue since all the test cases are done.
