### ISSUE TITLE
Recordset Directive Changes

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/chaise#1451]
Currently we have three different directive/templates for recordset.

1. RecordsetWithFaceting (RSwF): We should use this directive in most places.
2. Recordset (RS): This should be retired.
3. RecordsetSelectFaceting (RSSF): It's only being used for selecting facets. Since we needed a different template we're using a different directive too. The template should be modified to have faceting and it should use the flow-control.

These are the set of tasks that we should do in order to cleanup these directives:

#### General Improvements

- [x] Change `recordset-with-faceting` to have a collapsed state.
- [x] Make sure `recordset-with-faceting` directive has all the features of `recordset`. One feature that comes to my mind is getting the disabled tuples. A feature used in multi-picker for P&B association.
- [x] Change `SearchPopupController` to use `recordset-with-faceting` instead of `recordset`.
- [x] Change the behavior of RSwF from `ng-if` faceting to `ng-show`.
- [x] Change recordset app to be the same as other apps.

#### Removing RS directive and its template
- [x] Add the equivalent of `registerRecordsetCallbacks` for RSwF.
- [x] Make sure RSSF is using the newly added function, and it works (in a sense it should inherit RSwF and not RS). This includes adding `faceting` directive to it (although disabled).
- [x] Remove RS directive from recordset app. And remove the RS template and directive definition from project.

#### Getting rid of the old functionality and use the flow-control
- [x] Make sure `recordTable` directive is always using the `update` function (flow-control). 
- [x] Remove the unused utility functions from `recordTableUtils` factory.
- [x] Add a method to `recordTable` directive to be able to do the first read automatically.

#### Next Steps
- [ ] Remove selected rows list from RSSF and RSwF multi-picker (or maybe redesign it?).
- [x] (ermrestjs) Handle multiple layer of facets.
- [ ] Enable faceting in RSSF.

**Comment by RFSH** [comment]
If we want to add faceting to all the modal-pickers that we have, [we need changes in ermrestjs](https://github.com/informatics-isi-edu/ermrestjs/issues/603). The reason behind it is that one of the controls used in `recordset-with-faceting` is actually the modal-picker. So users eventually would be able to go deep into multiple levels of faceting and ermrestjs parser and faceting APIs don't support that. 

But based on the discussion in the meeting, we want this feature currently to go only one level deep. That means 
- the modal-picker in faceting won't have faceting in it (won't change to the user).
- The modal-picker for foreignkey (recordedit), and p&b association (record) will have faceting, but clicking on "show details" should open a modal without faceting.

To give a todo-list of what we need to do based on the discussion and also the issue description:

- [ ] Change `recordset-with-faceting` to have a collapsed state which is configured using annotation (**annotation draft needed**).
- [ ] Make sure `recordset-with-faceting` directive has all the features of `recordset`. One feature that comes to my mind is getting the disabled tuples. A feature used in multi-picker for P&B association.
- [ ] Change `SearchPopupController` to use `recordset-with-faceting` instead of `recordset`. 
   -  [ ] We should be able to completely remove the faceting for the case of faceting  (a new parameter is needed for the controller).
   -  [ ] It should have one level of faceting for foreignkey (recordedit), and p&b association (record)

**Comment by RFSH** [comment]
The last three steps, are the only remaining tasks on this epic.
- Remove selected rows list from RSSF and RSwF multi-picker (or maybe redesign it?).
- (ermrestjs) Handle multiple layer of facets.
-   Enable faceting in RSSF.

**Comment by RFSH** [comment]
I am going to close this issue since there's only one task is remaining in this epic and having this seems redundant.
