### ISSUE TITLE
history support

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#1502]
The goal is to make chaise/ermrestjs aware of versions, so that the navigation between pages (e.g. through RID or fks) are of the same version.

- [x] Make the apps aware of versions e.g. catalog@version. Currently, we just treat this as the catalog. 
- [ ] Linkages
  - [x] FK: when the fk link is generated, it should include the version from the current entity
  - [x] annotations: there are many cases where the linkage is done by annotations. In most of these cases, the annotation can be changed to use $fkeys.schema.table.values, so the version can be taken care of by ermrestjs. Do we need to provide some chaise parameters (examples below) to be used in the template?
    - $catalog.snapshot (e.g. 2@1234)
    - $catalog.version (e.g. 1234)
    - $catalog.id (e.g. 2)
    - ~$chaisePath.record (e.g. /chaise/record) --- this is needed to support multiple chaise deployments on one server~
    - ~$chaisePath.recordset~
    - ~$chaisePath.recordedit~
- [ ] navigation bar: should this be version dependent or display only the latest?  

@karlcz @robes @ljpearlman @bugacov Suggestions?

**Comment by RFSH** [comment]
To chaise/ermerstjs  catalog and catalog@version are the same. They only should know that there's a string for the catalog (which might or might not include version). This is the current assumption of chaise/ermestjs, but the only issue is that in some cases we're applying extra encoding/decoding which will cause inconsistencies. If we never apply encoding to the catalog and use it as is, chaise/ermrestjs should work with catalogs that have version. 

If we want this catalog string to be available in mustache, we can have something like `$catalog`. It doesn't have to be `$chaise.version`. But then I prefer if we come up with a mechanism like what we have for app-link. Instead of encouraging data modelers to create a link to chaise app from scratch (by doing something like `/chaise/recordset/#{{{$catalog}}}/s:t`).
