### ISSUE TITLE
Further viewer app changes

### ISSUE THREAD

**Issue by RFSH** [informatics-isi-edu/chaise#1983]
With the #1977 changes, viewer will now fetch the annotations from database and will allow users to add new annotations to the image. The following are the continuation of changes that we should do in viewer app:

- [x] Do the uniqueness check for the annotated term (anatomy) using some sort of configuration. We could pass the key constraint that should be used and use that one. The only issue with this method is how should we get the other column values? should we assume that they are not going to be visible? In the foreseeable feature, the values are coming either from the Image table, or derived from the image.
- [x] Investigate other ways of passing SVG URLs to osd viewer. With the current method, we're abusing query parameters. This solution is not scalable and eventually will hit the browser's url length limit.
- [x] Properly add logging support.
- [x] Remove the old and unused code to increase the readability of the code. 

_I created this issue so I can have a pointer for the viewer changes that I'm working on. I will keep updating this along the way._
