### ISSUE TITLE
Recordedit  > HTML structure > layout

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/chaise#2193]
By the end of this task, we want to have the HTML structure of the recordedit in place. Don't worry about different modes; only focus on the overall structure.

### Existing code
In [`react-recordedit-app`](https://github.com/informatics-isi-edu/chaise/tree/react-recordedit-app) branch, I implemented the skeleton of recordedit that you can work on. The following are the files that I added:

- [`src/pages/recordedit.tsx`](https://github.com/informatics-isi-edu/chaise/blob/react-recordedit-app/src/pages/recordedit.tsx): This is the entry point for the recordedit app. You don't need to worry about its content for this task.
- [`src/components/recordedit/recordedit.tsx`](https://github.com/informatics-isi-edu/chaise/blob/react-recordedit-app/src/components/recordedit/recordedit.tsx): This is the "recordedit" component. While record and recordedit "components" are only used in record/recordedit "apps", I followed the same pattern for all our apps so later we can have them outside of the app (in a modal for example). You should modify this file. If you want to add new components, please add them in the same `src/components/recordedit` folder.
- [ `src/assets/scss/_recordedit.scss`](https://github.com/informatics-isi-edu/chaise/blob/react-recordedit-app/src/assets/scss/_recordedit.scss): The styles that you're going to add should go here. Feel free to create new files for the components that you might create.

### Tasks

Before going through the list of tasks, please pay attention to the following:
- Please ensure you're replicating the same overall HTML structure as the master. So use the same `top-panel-container`/`bottom-panel-container` that you see in all our apps. The scrollable section of the page relies on these classes, and keeping the same structure will reduce the number of style changes you need to do. The following is how the overall structure should be:

```html
<div class="app-content-container">
  <div class='top-panel-container'>
    <!--- Alerts should be used here -->
    <div class="top-flex-panel">
     <!-- this is just for consistency with all apps: -->
      <div class="top-left-panel close-panel"></div>
      <div class="top-right-panel">
         <!-- TODO title and buttons go here -->
      </div>
    </div>
  </div>
  <div class="bottom-panel-container">
    <!-- this is just for consistency with all apps: -->
    <div class="side-panel-resizable close-panel"></div>
    <div class="main-container">
      <div class="main-body">
         <!--- TODO the form goes here -->
      </div>
    </div>
  </div>
</div>
```

- Recordedit supports create, edit, and copy modes. But in this task, we will assume it's in create mode. 

- It's better if you deploy both the master and react branches on a server and have them side by side while working on the changes.

In the following, you can find the list of tasks. Starting from the top and working down the page should be a good place to start.

 - [x] Navbar and "top-panel" should be sticky, while the rest of the page is scrollable. For this, you just need to make sure to replicate the same page structure as the master (and all the other apps that we have), and then call `attachContainerHeightSensors` in a `useLayoutEffect` like [here](https://github.com/informatics-isi-edu/chaise/blob/react-recordedit-app/src/components/record/record.tsx#L138)
- [x] Title bar
  - [x] Display title information with the proper link (as I mentioned, assume "create" mode for now).
  - [x] Save button (Just the placeholder button without any onClick handler)
  - [x] Clone button for duplicating the last form 1 or x times
    - [x] UI with multiple forms after adding 1 form, adding x forms
- [x] column names
  - [x] Proper sticky behavior
  - [x] `reference.columns` will give you the list of columns. And then, for each column, you can use the following properties:
    - [x] `reference.columns[i].displayname` will give you their displayname that can be passed to the `DisplayValue` components. 
    - [x] `reference.columns[i].comment` will give you the tooltip string. If it's defined, display it. Take a look at other apps for examples of how this is done.
    - [x] `reference.columns[i].nullok` returns a boolean that can be used for the logic of showing the "required" indicator.
- [x] form layout
  - [x] Expand the input switch to support "text" type. 
  - [x] Use input-switch in the form (use the "text" type for all the columns for now).
  - [x] support multiple forms on the page.
  - [x] "delete" button for each form.
  - [x] Proper scroll behavior (with an additional horizontal scrollbar above the form).

**Comment by jrchudy** [comment]
This functionality is complete and merged into the `react-recordedit-app` branch.
