### ISSUE TITLE
Login status changed issues

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/chaise#2398]
This issue is created to track all the changes to be done to finalize the `login status changed` epic. Listing the issues and what to do to resolve each one":
 - [ ] Remove autosubmit (#1930) discuss the following:
   - steps to take in issue:
     - Change modal to suggestion for point 2 in issue
     - Change session expired title for point 3 in issue
     - Swap the buttons for point 4 in issue
   - should this be applied to other modals with similar flow?
 - [ ] How to continue after signing in on page with permissioned read requests (#1916):
   - discuss the contents of the issue for different scenarios
 - [ ] Improve session timed out while interacting with page (#1918):
   - discuss how to better address change of login status while page is stale
     - session expired while away from computer for 30+ minutes
     - permissions changed in ermrest while page hasn't refreshed
 - [ ] improve login modals to not allow cancel if the app state would be degraded or unusable (#2322)
   - discuss what to do for each scenario in issue

Regarding hatrac file uploads when login status change and is fixed:
 - [ ] File upload job reset on 401 (#1837):
   - Don't force user to restart upload if logging back into the same user if session times out
