### ISSUE TITLE
Minimal data entry form

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#334]
The minimal data entry form should support:

- [x] vertical layout
- [x] type specific data entry for text, integer, date, boolean
- [x] client-side data validation
- [x] serial columns should not allow input
- [x] submit or save should take user to record or recordset page
- [x] error handling (there are many error cases that should be considered)

We should convert this list into tasks within this epic.

**Comment by robes** [comment]
I would expect this to take about 5 days roughly...
