### ISSUE TITLE
Record 2, Round 1

### ISSUE THREAD

**Issue by howdyjessie** [informatics-isi-edu/chaise#456]
**General**
- [ ] Set up unit test structure? (see Viewer app)
- [ ] As close to 100% unit test coverage
- [ ] All special characters in the column names and values shown in the URL are escaped properly (#373)

**Setting Up the App / Config & Run Blocks**
- [x] When parsing the URL to determine the requested entity, Common tasks like getting the catalog number, schema name, and table name, and getting  should be put into `common/`.
- [x] Use `$rootscope` instead of a `context` value provider to store global variables such as the catalog number, schema name, table name, etc.
 - Be careful to only store globals and constants needed across the entire app.`$rootscope` should be treated as a read-only data store after config and run has executed.

**Main Entity**
- [x] Display row name
  - A function to retrieve a row name (a.k.a., title):
    - If a ~~title~~ `2015:display.row_name` annotation exists, use that instead.
    - Default: Look for a column with `title`, `name`, or `label` (case insensitive) and display that
    - This should be implemented in ermrestjs as a function that can compute the row name. This hasn't been thought out yet, but one idea would be a function on the RowSet returned by a the get(...) APIs.
  - _new ermrestjs feature needed_
- [x] Display record table name:
  - Ermrestjs will always have table display_name:
    - If table has `2015:display.name` annotation, show that instead.
    - Default: Table name
    - Feature exists in ermrestjs. Use `<table instance>.displayname`
- [x] Display record columns in the right order and correctly
  - order
    - If a 2015:display.column_order annotation exists, show the columns in the annotation's specified order.
    - Default: Show columns in the order defined in the database
    - Ermrestjs returns column definition instances from the `Columns.all()` function and that function should be updated to return the column definitions in the appropriate order per heuristics or annotations.
  - visibility: If 2016:ignore is there, ignore the column
  - _new ermrestjs feature needed_
- [x] Show the right presentation depending on the column type (common code or ermrestjs)
  - date
  - timestamp
  - float
  - markdown
  - We need to decide what parts of this can be in ermrestjs and what parts need to be in some chaise common.
- [x] null handling: 
  - ~~Columns with `null` value should be skipped/hidden~~ This is wrong for editable records where a user needs to realize there are null values to edit. If this hiding is important, needs some new annotation control and SHOULD NOT be the default for regular tables.
  - eventually, this can be controlled at the UI level
  - _new ermrestjs feature needed_

**Column Display**
 - [x] Show the correct title if the column has the 2015:display.name annotation
 - [ ] Use display name hueristics annotation to determine the display name transformation e.g. "My_Table" -> "My Table" or "my_table" -> "My Table". 
    - _new ermrestjs feature needed_
 - [x] Default: Display the name as is.

**Tooltip**
 - [x] Show a tooltip if a table or column of the main entity has a ~~tooltip annotation~~ comment resource. The tooltip should appear when moused over.
 - Maybe _new ermrestjs feature needed_. We may want to add a `<columninstance>.tooltip` property.

**chaise config**
- [ ] Review/update the config structure (Rob)
- [ ] Landing page

**Comment by karlcz** [comment]
Every single reference to an annotation other than 2015:... or 2016:... as defined in the ermrest/user-doc/annotation.md MUST be removed or replaced.  This new app should not be implementing *any* pof the legacy annotations from older apps.

**Comment by robes** [comment]
Regarding annotations. In general I'd like to consume more annotations (when applicable) at the ermestjs layer and reduce the amount of conditional logic in the application layer. This is possible when ermrestjs doesn't need to know the application context-specific annotations.

**Comment by robes** [comment]
Also, we still do not have a specification for what the record app is and should support. This epic and the wiki page are written with underlying assumptions.

**Comment by robes** [comment]
Mike requests we make it easier to swap in or override style sheet stuff.

**Comment by robes** [comment]
@howdyjessie @jrchudy This should be modular such that there is an 'app' that is a composition of 'components'. This round 1 essentially describes the component that does the core row display. The row display component should be usable not only in this record2 app but also if we were to plug it into the 2d image annotation viewer in the metadata tab. Hope this is clear. We can discuss this further.

**Comment by robes** [comment]
We also decided that this `record2` app can coexist with the `record` app. That way any of our CI servers can simply be configured to use record2 instead of record, if we want to test it out.

**Comment by hongsudt** [comment]
I am closing this epic since the round 1 is done.
